# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import pandas as pd
            import glob
            import os
            import numpy


            find_files = os.path.join(r'C:\Users\antho\OneDrive - The University of Texas at Dallas\Documents\GitHub\PMG-Coding_Challenge', '*.csv')


            list_files = glob.glob(find_files)

            df = pd.concat(map(pd.read_csv, list_files), ignore_index=False, keys=['accessories.csv', 'clothing.csv'], names=['filename'])
            print(df)
